config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'

  root 'static_pages#index'
  resources :gossips do
    resources :comments
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
  validates :password, presence: true, length: {minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = []
    @users = @city.users
    @users.each do |u|
      u.gossips.each do |g|
        @gossips << g
      end
    end
    puts "*" * 60
    puts @gossips
    puts "*" * 60

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def index
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.find(params[:id])
    @comment = @gossip.comment.new
  end

  def create
    @comment = Comment.create(content: params[:content], user_id: session[:user_id] , gossip_id: params[:gossip_id])
    redirect_to gossip_path(params[:gossip_id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    comment_params = params.permit(:content)

      if @comment.update(comment_params)
        redirect_to gossip_path(params[:gossip_id])
      else
        render :edit
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(params[:gossip_id])
  end

  def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new]
  before_action :author_gossip, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.all
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
    @comments = @gossip.comments
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
    @user_id = session[:user_id]
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id] )

    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to root_path, :notice => "Potin créé !"
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)

      if @gossip.update(gossip_params)
        # flash[:notice] = "Gossip mis à jour"
        redirect_to @gossip, :notice => "Gossip mis à jour"
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
        flash[:danger] = "Connecte-toi ;)"
        redirect_to new_session_path
    end
  end

  def author_gossip
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
        flash[:danger] = "Tu n'es pas l'auteur de ce potin."
        redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new #new qui correspond à la page de login
  end

  def create
    user = User.find_by(email: params[:email])

    # on vérifie si l'utilisateur existe bien
    # ET si on arrive à l'authentifier (méthode bcrypt)
    # avec le mot de passe
    if user && user.authenticate(params[:password])
      log_in(user)
      flash[:notice] = "Vous êtes connecté"
      redirect_to root_path
      # redirige où tu veux, avec un flash ou pas
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
    @gossip = Gossip.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def user_params
  #   params.permit(:first_name, :last_name, :description, :email, :age, :password, :confpassword)
  # end

  def index
    @users = User.all
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    puts "*" * 60
    puts params
    puts "*" * 60
    @user = User.new(first_name: params[:first_name],
                     last_name: params[:last_name],
                     description: params[:description],
                     email: params[:email],
                     age: params[:age],
                     password: params[:password],
                     city_id: City.all.sample.id)

    if @user.save # essaie de sauvegarder en base @gossip
      log_in(@user)
      redirect_to root_path, :notice => "Bienvenue #{@user.first_name} !"
    else
      render 'new'
    end
    # Par rapport à ce qu'on a vu jusque-là,
    # la méthode #create du controller users ne change quasiment pas.
    # Simplement, il faut récupérer le mot de passe depuis le formulaire d'inscription
    # (via params) et faire un simple User.new(email: "xxx",
    # password: "yyy"). La gem bcrypt s'occupe de tout côté model pour
    # encrypter le password : Fat model, skinny controller !
    # User.new(email: "xxx", password: "yyy")
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
        puts "Voici le message de l'URL :"
        puts  params[:user_entry]
        puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<div class="card border-info m-5">
 <div class="card-header"><h1><i class="fas fa-edit"></i> Édite le potin n° <%= params[:id] %></h1></div>

  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= label_tag 'Titre'%>
          <%= text_field_tag :title, @gossip.title, class:'form-control', placeholder: @gossip.title %>
          <br /> <br />

          <%= label_tag 'Contenu du potin' %>
          <%= text_area_tag :content, @gossip.content, class:'form-control', placeholder: @gossip.content %>
          <br /> <br />

          <%= submit_tag "Éditer le potin", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>


  </div>
</div>

<% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
      <% end %>

app/views/gossips/index.html.erb
<% if flash.now[:notice] %>
<div class="alert alert-success">
  <div class="notice">
    <%= flash.now[:notice] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>

  <h1 class="text-center m-4"><i class="fas fa-comments"></i> Tous les potins</h1>

  <div class="card-columns border-info container">
    <% @gossips.each do |i| %>
      <div class="card" style="width: 18rem;">
        <div class="card-header"><h5 class="card-title"><%= i.title %> <span class="badge badge-secondary">
      <i class="fas fa-comments"></i> <%= i.comments.count %></span></h5>
        <%= i.comments.count %>
        </div>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted"><%= i.user.first_name %></h6>
          <%= link_to "Go Potin", gossip_path(i.id),:class => "btn-info btn p-1"%>
        </div>
      </div>
    <% end %>
</div>

app/views/gossips/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Ajouter un potin</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= text_field_tag 'title', @gossip.title, class: "form-control", placeholder: "Le titre de ton potin" %>
          <%= text_area_tag 'content', @gossip.content, class: "form-control", placeholder: "Ton potin" %>
          <br /> <br />

          <%= submit_tag "Ajouter mon potin", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>
</div>
    <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
      <% end %>

app/views/gossips/show.html.erb
<% if flash.now[:notice] %>
<div class="alert alert-success">
  <div class="notice">
    <%= flash.now[:notice] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>
<div class="card border-info text-center m-5">
  <div class="card-header">
    <p class="text-right text-muted">
      <i class="fas fa-edit"></i> <%= link_to "Éditer le potin", edit_gossip_path(params[:id]) %>&nbsp;&nbsp;
      <i class="fas fa-trash-alt"></i> <%= link_to "Supprimer le potin", gossip_path(params[:id]), type: "submit", method: "delete", data: { confirm: "Tu es sûr-e ?" }  %>
    </p>
    <h1><i class="fas fa-comment"></i> <u><%= @gossip.title %></u> <small class="text-muted">(Potin n° <%= params[:id] %>)</small></h1>
  </div>

  <div class="card-body text-info">
    <blockquote class="blockquote">
      <p class="m-2"><%= @gossip.content %></p>
        <footer class="blockquote-footer">
          <cite title="Auteur du potin">
            <%= link_to @gossip.user.first_name + " " + @gossip.user.last_name, user_path(@user.id) %>
          </cite>
          de la ville de <%= @gossip.user.city.name %>
        </footer>
      </blockquote>
  </div>
  <div class="card-footer text-muted text-right"><i class="far fa-clock"></i> <%= @gossip.created_at %></div>
</div>

<!-- Ajouter un commentaire  -->
<div class="card m-5">
 <div class="card-header">
  <h2>Ajouter un commentaire</h2>
  </div>
  <%= form_tag(gossip_comments_path(params[:id]), method: :create) do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div class="card-body text-info">
    <div class="form-group">
      <%= label_tag 'Contenu du commentaire' %>
      <%= text_area_tag 'content', @comment.content, class: "form-control", placeholder: "Ton commentaire" %>
      <br /> <br />

      <%= submit_tag "Ajouter un commentaire", class: "btn btn-info" %>
  <% end %>
    </div>
  </div>
</div>

<!-- Affichage des commentaires -->
<h1 class="text-center m-4"><i class="far fa-comments"></i> Tous les commentaires</h1>

  <div class="card-columns border-info container">
    <% @comments.each do |c| %>
      <div class="card">
        <div class="card-body">
        <h5 class="card-title"><i class="far fa-comment"></i> <%= c.content %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><i class="far fa-user"></i> <%= c.user.first_name + " " + c.user.last_name %></h6>
          <i class="fas fa-edit"></i> <%= link_to "Éditer", edit_gossip_comment_path(@gossip.id, c.id) %>&nbsp;&nbsp;
          <i class="fas fa-trash-alt"></i> <%= link_to "Supprimer", gossip_comment_path(@gossip.id, c.id), type: "submit", method: "delete", data: { confirm: "Tu es sûr-e ?" }  %>
        </div>
      </div>


    <% end %>
</div>

app/views/users/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Créer son compte</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div class="card-body text-info">
      <div class="form-group">
        <%= text_field_tag 'first_name', '', class: "form-control", placeholder: "Prénom" %>
        <%= text_field_tag 'last_name', '', class: "form-control", placeholder: "Nom" %>
        <%= text_field_tag 'description', '', class: "form-control", placeholder: "Description" %>
        <%= text_field_tag 'age', '', class: "form-control", placeholder: "Âge" %>
        <%= text_field_tag 'email', '', class: "form-control", placeholder: "Email" %>
        <%= password_field_tag 'password', '', class: "form-control", placeholder: "Mot de passe" %>
        <br /> <br />
        <%= submit_tag "Je m'inscris !", class: "btn btn-info" %>
      <p class="mt-4">Déjà un compte ? <%= link_to "Je me connecte !", new_session_path %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="card border-info m-5 text-center">
  <div class="card-header">
    <h1><i class="fas fa-user"></i> <u><%= @user.first_name + " " + @user.last_name  %></u></h1>
  </div>
  <div class="card-body text-info">
    <ul class="card-text list-group">
      <li class="list-group-item">Prénom : <%= @user.first_name %></li>
      <li class="list-group-item">Nom : <%= @user.last_name %></li>
      <li class="list-group-item">Description : <%= @user.description %></li>
      <li class="list-group-item">Email : <%= @user.email %></li>
      <li class="list-group-item">Âge : <%= @user.age %></li>
      <li class="list-group-item">Ville : <%= link_to @user.city.name , city_path(@user.city.id),:class => ""%></li>
    </ul>
  </div>
  <div>
    <%= link_to "ville de " + @user.city.name , city_path(@user.city.id),:class => "btn-info btn m-2"%>
  </div>
</div>


<h2 class="text-center mb-5">Potins de <%= @user.first_name %> </h2>
<div class="card-columns border-info container">
  <% @user.gossips.each do |i| %>
    <div class="card" style="width: 18rem;">
      <div class="card-header"><h5 class="card-title"><%= i.title %></h5></div>
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= i.user.first_name %></h6>
        <%= link_to "Go Potin", gossip_path(i.id),:class => "btn-info btn p-1"%>
      </div>
    </div>
  <% end %>
</div>