config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'

  root 'static_pages#index'
  resources :gossips do
    resources :comments
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
  validates :password, presence: true, length: {minimum: 6}

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = []
    @users = @city.users
    @users.each do |u|
      u.gossips.each do |g|
        @gossips << g
      end
    end
    puts "*" * 60
    puts @gossips
    puts "*" * 60

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def index
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.find(params[:id])
    @comment = @gossip.comment.new
  end

  def create
    @comment = Comment.create(content: params[:content], user_id: session[:user_id] , gossip_id: params[:gossip_id])
    redirect_to gossip_path(params[:gossip_id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    comment_params = params.permit(:content)

      if @comment.update(comment_params)
        redirect_to gossip_path(params[:gossip_id])
      else
        render :edit
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(params[:gossip_id])
  end

  def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new]
  before_action :author_gossip, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.all
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
    @comments = @gossip.comments
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
    @user_id = session[:user_id]
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id] )

    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to root_path, :notice => "Potin créé !"
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)

      if @gossip.update(gossip_params)
        # flash[:notice] = "Gossip mis à jour"
        redirect_to @gossip, :notice => "Gossip mis à jour"
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
        flash[:danger] = "Connecte-toi ;)"
        redirect_to new_session_path
    end
  end

  def author_gossip
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
        flash[:danger] = "Tu n'es pas l'auteur de ce potin."
        redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def user_params
  #   params.permit(:first_name, :last_name, :description, :email, :age, :password, :confpassword)
  # end

  def index
    @users = User.all
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    puts "*" * 60
    puts params
    puts "*" * 60
    @user = User.new(first_name: params[:first_name],
                     last_name: params[:last_name],
                     description: params[:description],
                     email: params[:email],
                     age: params[:age],
                     password: params[:password],
                     city_id: City.all.sample.id)

    if @user.save # essaie de sauvegarder en base @gossip
      log_in(@user)
      redirect_to root_path, :notice => "Bienvenue #{@user.first_name} !"
    else
      render 'new'
    end
    # Par rapport à ce qu'on a vu jusque-là,
    # la méthode #create du controller users ne change quasiment pas.
    # Simplement, il faut récupérer le mot de passe depuis le formulaire d'inscription
    # (via params) et faire un simple User.new(email: "xxx",
    # password: "yyy"). La gem bcrypt s'occupe de tout côté model pour
    # encrypter le password : Fat model, skinny controller !
    # User.new(email: "xxx", password: "yyy")
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
        puts "Voici le message de l'URL :"
        puts  params[:user_entry]
        puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Gossip</title>
  <meta charset="utf-8">
  <meta name="viewport"
      content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
  </style>
</head>

<body>
<header>
    <nav class="navbar navbar-inverse">
      <%= link_to "GOSSIP", root_path, :class => "navbar-brand" %>

      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle"
              data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <%= link_to "Contact", contact_path, :class => "navbar-brand" %>
            <%= link_to "Team", team_path, :class => "navbar-brand" %>
            <% if session[:user_id] != nil %>
              <%= link_to "Ajouter un potin", new_gossip_path, :class => "navbar-brand" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>

<div class="container text-center">
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <% if session[:user_id] != nil %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name %>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Profil", user_path(session[:user_id]), :class => "dropdown-item" %>
                <br>
                <%= link_to "Se déconnecter", session_path(session[:user_id]), method: :delete, data: { confirm: "Tu es sûr-e ?" }, :class => "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Connexion / Inscription
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Se connecter", new_session_path, :class => "dropdown-item" %>
                <br>
                <%= link_to "S'inscrire", new_user_path, :class => "dropdown-item" %>
              </div>
            </div>
          <% end %>
        <img src="https://i.kym-cdn.com/photos/images/original/000/456/353/05a.jpg" class="img-circle" height="100" width="150" alt="Avatar">
      </div>
      <p><a href="https://www.newgrounds.com/portal/view/484667">Petits</a></p>
      <p><a href="https://www.youtube.com/watch?v=MweBROloGlI">Liens</a></p>
      <p><a href="https://www.youtube.com/watch?v=l7bprvrJaO8">Bonus</a></p>
    </div>

    <div class="col-sm-7">
          <%= yield %>
    </div>

    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>The Place to be:</p>
        <img src="https://clecy.stationverte.com/visuels/full/670_o5V243.jpg"
          alt="Clécy" width="400" height="300">
        <p><strong>Clécy</strong></p>
        <p>Jeudi 07 Fevrier 2019</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Salut ça boom?</p>
</footer>

</body>
</html>